version: '3'

services:
  frontend:
    build: ./frontend-app
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build: ./flask-app
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: sampledb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
